name: Publish Package to npmjs
on:
    push:
      tags:
        - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          VERSION=$(echo ${{ github.ref_name }} | sed -e 's/v//')
          TAG=latest
          if [[ $VERSION == *"beta"* ]]; then
            TAG = "beta"
          fi
          if [[ $VERSION == *"alpha"* ]]; then
            TAG = "alpha"
          fi
          npm version ${VERSION} --tag $TAG --no-commmit-hooks --no-git-tag-version
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}