name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          export VERSION=$(echo ${{ github.ref_name }} | sed -e 's/v//')
          export TAG="latest"
          if [[ $VERSION == *"beta"* ]]; then
            export TAG="beta"
          fi
          if [[ $VERSION == *"alpha"* ]]; then
            export TAG="alpha"
          fi
          npm version ${VERSION} --no-commmit-hooks --no-git-tag-version
          pnpm install --frozen-lockfile
          npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}